### PR TITLE
Some corrections and enhancements

### PR DESCRIPTION
**Pull request by sgdc3**
1) We should use tabs with xml files
2) We should use spigot-api instead the bukkit one
3) Removed useless repos
4) Removed shade (useless)
5) Readded exclusions
6) Fixed circle ci compatibility
7) Removed useless resource options
8) The jar name should be NAME-VERSION.jar 
9) Readded version replace in plugin.yml

### CODE REVIEW

**Comment by confuser** [comment]
1) Why? If code has spaces, standards are to use spaces in all files, not mix and match
2) Why? Spigot API has no benefits over Bukkit, and it means anyone running craftbukkit instead of spigot won't be able to use this plugin.
3) Fair enough
4) Shading is not useless, it avoid conflicts with plugins that have the same namespace. This is going to cause problems.
7) Not useless, it allows using maven variables in the resource files, e.g. version
8) Entirely subjective, it's easier to mass update plugins when they're not versioned, and as the owner of one of the oldest minecraft networks in the community I disagree with this change
9) See 7

**Comment by sgdc3** [comment]
Ok, done :)

**Comment by sgdc3** [comment]
It's ok now?

**Comment by sgdc3** [comment]
@confuser

**Comment by sgdc3** [comment]
@confuser What do you think about it now?

**Comment by confuser** [comment]
Please wait until I'm complete.

**Comment by sgdc3** [comment]
ok

**Pull request closed without merging**
